import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "electronics",
    price: 89999,
    originalPrice: 124999,
    discount: 28,
    rating: 4.8,
    reviews: 1250,
    minOrder: 10,
    image: "/samsung-galaxy-s24-ultra.png",
    description: "Latest flagship smartphone with S Pen, 200MP camera, and AI features",
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Storage: "256GB",
      RAM: "12GB",
      Camera: "200MP + 50MP + 12MP + 10MP",
    },
    inStock: true,
  },
  {
    id: "2",
    name: "Nike Air Max 270",
    brand: "Nike",
    category: "footwear",
    price: 8999,
    originalPrice: 12995,
    discount: 31,
    rating: 4.6,
    reviews: 890,
    minOrder: 20,
    image: "/nike-air-max-270-running-shoes.jpg",
    description: "Comfortable running shoes with Max Air unit for superior cushioning",
    specifications: {
      Material: "Mesh and synthetic leather",
      Sole: "Rubber with Air Max technology",
      Sizes: "6-12 UK",
      Colors: "Multiple variants available",
    },
    inStock: true,
  },
  {
    id: "3",
    name: "Adidas Ultraboost 22",
    brand: "Adidas",
    category: "footwear",
    price: 11999,
    originalPrice: 16999,
    discount: 29,
    rating: 4.7,
    reviews: 654,
    minOrder: 15,
    image: "/adidas-ultraboost-22-running-shoes.jpg",
    description: "Premium running shoes with Boost midsole technology",
    specifications: {
      Material: "Primeknit upper",
      Technology: "Boost midsole",
      Sizes: "6-12 UK",
      Weight: "320g",
    },
    inStock: true,
  },
  {
    id: "4",
    name: "Apple iPhone 15 Pro",
    brand: "Apple",
    category: "electronics",
    price: 124999,
    originalPrice: 134900,
    discount: 7,
    rating: 4.9,
    reviews: 2100,
    minOrder: 5,
    image: "/iphone-15-pro.png",
    description: "Pro-level iPhone with titanium design and advanced camera system",
    specifications: {
      Display: "6.1-inch Super Retina XDR",
      Storage: "128GB",
      Chip: "A17 Pro",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
    },
    inStock: true,
  },
  {
    id: "5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "electronics",
    price: 24999,
    originalPrice: 29990,
    discount: 17,
    rating: 4.8,
    reviews: 756,
    minOrder: 25,
    image: "/sony-wh-1000xm5-wireless-headphones.jpg",
    description: "Premium noise-canceling wireless headphones with 30-hour battery",
    specifications: {
      Battery: "30 hours",
      Connectivity: "Bluetooth 5.2",
      Features: "Active Noise Canceling",
      Weight: "250g",
    },
    inStock: true,
  },
  {
    id: "6",
    name: "Puma RS-X Sneakers",
    brand: "Puma",
    category: "footwear",
    price: 6999,
    originalPrice: 9999,
    discount: 30,
    rating: 4.4,
    reviews: 432,
    minOrder: 30,
    image: "/puma-rs-x-sneakers-casual-shoes.jpg",
    description: "Retro-inspired sneakers with bold design and comfortable fit",
    specifications: {
      Material: "Synthetic leather and mesh",
      Sole: "Rubber outsole",
      Sizes: "6-12 UK",
      Style: "Casual/Lifestyle",
    },
    inStock: true,
  },
  {
    id: "7",
    name: "Dell XPS 13 Laptop",
    brand: "Dell",
    category: "electronics",
    price: 89999,
    originalPrice: 109999,
    discount: 18,
    rating: 4.6,
    reviews: 543,
    minOrder: 8,
    image: "/dell-xps-13-laptop-computer.jpg",
    description: "Ultra-portable laptop with InfinityEdge display and premium build",
    specifications: {
      Processor: "Intel Core i7-1360P",
      RAM: "16GB LPDDR5",
      Storage: "512GB SSD",
      Display: "13.4-inch FHD+",
    },
    inStock: true,
  },
  {
    id: "8",
    name: "VIP Trolley Bag 75cm",
    brand: "VIP",
    category: "luggage",
    price: 4999,
    originalPrice: 7999,
    discount: 38,
    rating: 4.3,
    reviews: 321,
    minOrder: 50,
    image: "/vip-trolley-bag-luggage-suitcase.jpg",
    description: "Large trolley bag with 4-wheel system and TSA lock",
    specifications: {
      Size: "75cm (Large)",
      Material: "Polycarbonate",
      Wheels: "4-wheel spinner",
      Weight: "3.2kg",
    },
    inStock: true,
  },
  {
    id: "9",
    name: "Fossil Gen 6 Smartwatch",
    brand: "Fossil",
    category: "accessories",
    price: 18999,
    originalPrice: 24995,
    discount: 24,
    rating: 4.5,
    reviews: 287,
    minOrder: 20,
    image: "/fossil-gen-6-smartwatch-wearable.jpg",
    description: "Wear OS smartwatch with heart rate monitoring and GPS",
    specifications: {
      OS: "Wear OS by Google",
      Battery: "24+ hours",
      Display: "1.28-inch AMOLED",
      Features: "Heart rate, GPS, NFC",
    },
    inStock: true,
  },
  {
    id: "10",
    name: "Lakme Absolute Makeup Kit",
    brand: "Lakme",
    category: "fmcg",
    price: 2999,
    originalPrice: 4500,
    discount: 33,
    rating: 4.2,
    reviews: 198,
    minOrder: 100,
    image: "/lakme-makeup-kit-cosmetics-set.jpg",
    description: "Complete makeup kit with foundation, lipstick, and eye makeup",
    specifications: {
      Items: "Foundation, Lipstick, Mascara, Eyeliner",
      "Skin Type": "All skin types",
      Finish: "Matte and glossy options",
      "Shelf Life": "24 months",
    },
    inStock: true,
  },
  {
    id: "11",
    name: "Levi's 511 Slim Jeans",
    brand: "Levi's",
    category: "garments",
    segment: "womens",
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 4.4,
    reviews: 567,
    minOrder: 40,
    image: "/levis-511-slim-fit-jeans-denim.jpg",
    description: "Classic slim-fit jeans with authentic Levi's styling",
    specifications: {
      Fit: "Slim",
      Material: "98% Cotton, 2% Elastane",
      Sizes: "28-38 waist",
      Colors: "Blue, Black, Grey",
    },
    inStock: true,
  },
  {
    id: "13",
    name: "Peter England Formal Shirt",
    brand: "Peter England",
    category: "garments",
    segment: "mens",
    price: 1999,
    originalPrice: 2799,
    discount: 29,
    rating: 4.3,
    reviews: 210,
    minOrder: 60,
    image: "/placeholder.jpg",
    description: "Cotton formal shirt ideal for office wear",
    specifications: {
      Fit: "Regular",
      Material: "100% Cotton",
      Sizes: "38-44",
      Color: "White",
    },
    inStock: true,
  },
  {
    id: "14",
    name: "Nike Kids Sports T-Shirt",
    brand: "Nike",
    category: "garments",
    segment: "kids",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.5,
    reviews: 145,
    minOrder: 80,
    image: "/placeholder.jpg",
    description: "Breathable performance tee for active kids",
    specifications: {
      Sizes: "6-14 years",
      Material: "Polyester",
      Colors: "Blue, Red",
      Style: "Sportswear",
    },
    inStock: true,
  },
  {
    id: "15",
    name: "Prestige Pressure Cooker 5L",
    brand: "Prestige",
    category: "kitchen",
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    rating: 4.2,
    reviews: 380,
    minOrder: 40,
    image: "/placeholder.jpg",
    description: "Aluminum 5L pressure cooker suitable for bulk kitchen needs",
    specifications: {
      Capacity: "5 Liters",
      Material: "Aluminum",
      Warranty: "5 years",
      Compatibility: "Gas stove",
    },
    inStock: true,
  },
]
